APIProject-MovieAPI/Models/FavoriteMovies.cs
using System;
using System.Collections.Generic;

namespace APIProject_MovieAPI.Models
{
    public partial class FavoriteMovies
    {
        public int MovieId { get; set; }
        public string UserId { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }
        public string Rated { get; set; }
        public string Runtime { get; set; }
        public string Director { get; set; }
        public string Genre { get; set; }

        public virtual AspNetUsers User { get; set; }
    }
}

APIProject-MovieAPI/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace APIProject_MovieAPI.Models
{
    public class MovieList
    {
        public Movie[] Search { get; set; }
        public string totalResults { get; set; }
        public string Response { get; set; }
    }
    public class Movie
    {
        public string Title { get; set; }
        public string Year { get; set; }
        public string Rated { get; set; }
        public string Released { get; set; }
        public string Runtime { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        public string Writer { get; set; }
        public string Actors { get; set; }
        public string Plot { get; set; }
        public string Language { get; set; }
        public string Country { get; set; }
        public string Awards { get; set; }
        public string Poster { get; set; }
        public Rating[] Ratings { get; set; }
        public string Metascore { get; set; }
        public string imdbRating { get; set; }
        public string imdbVotes { get; set; }
        public string imdbID { get; set; }
        public string Type { get; set; }
        public string DVD { get; set; }
        public string BoxOffice { get; set; }
        public string Production { get; set; }
        public string Website { get; set; }
        public string Response { get; set; }
    }

    public class Rating
    {
        public string Source { get; set; }
        public string Value { get; set; }
    }

}

APIProject-MovieAPI/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using APIProject_MovieAPI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Protocols;

namespace APIProject_MovieAPI.Controllers
{
    [Authorize]
    public class MovieController : Controller
    {
        private readonly CinemaContext _context;
        private readonly IConfiguration _configuration;
        private readonly string _apiKey;

        public MovieController(CinemaContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
            _apiKey = _configuration.GetSection("AppConfiguration")["APIKey"];

        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> SearchByTitle(string title, int year)
        {
            string yearstring = year.ToString();
            if (year != 0)
            {
                title.Replace(" ", "+");
                var client = GetHttpClient();
                var response = await client.GetAsync($"?s={title}&y={yearstring}&apikey={_apiKey}");
                var name = await response.Content.ReadAsAsync<MovieList>();
                return View(name);
            }
            else
            {
                title.Replace(" ", "+");
                var client = GetHttpClient();
                var response = await client.GetAsync($"?s={title}&apikey={_apiKey}");
                var name = await response.Content.ReadAsAsync<MovieList>();
                return View(name);
            }
        }
        public async Task<IActionResult> Details(Movie movie)
        {
            var client = GetHttpClient();
            var yearstring = movie.Year;
            var title = movie.Title;
            title.Replace(" ", "+");
            var response = await client.GetAsync($"?t={title}&y={yearstring}&apikey={_apiKey}");
            var name = await response.Content.ReadAsAsync<Movie>();
            return View(name);
        }
        public static HttpClient GetHttpClient()
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("http://www.omdbapi.com");
            return client;
        }
            public IActionResult AddFavorite(Movie movie)
        {
            AspNetUsers thisUser = _context.AspNetUsers.Where(u => u.UserName == User.Identity.Name).First();
            FavoriteMovies favorite = new FavoriteMovies();

            if (ModelState.IsValid)
            {
                favorite.UserId = thisUser.Id;
                favorite.Director = movie.Director;
                favorite.Rated = movie.Rated;
                favorite.Runtime = movie.Runtime;
                favorite.Title = movie.Title;
                favorite.Year = movie.Year;
                favorite.Genre = movie.Genre;

                _context.FavoriteMovies.Add(favorite);
                _context.SaveChanges();
                return RedirectToAction("FavoriteMovies");
            }
           return RedirectToAction("Index");
        }
    public IActionResult FavoriteMovies()
        {
            AspNetUsers thisUser = _context.AspNetUsers.Where(u => u.UserName == User.Identity.Name).First();
            List<FavoriteMovies> favoriteList = _context.FavoriteMovies.Where(u => u.UserId == thisUser.Id).ToList();
            return View(favoriteList);
        }

        public IActionResult DeleteFavorite(FavoriteMovies movie)
        {
            if(movie != null)
            {
                _context.FavoriteMovies.Remove(movie);
                _context.SaveChanges();
                return RedirectToAction("FavoriteMovies");
            }
            return RedirectToAction("FavoriteMovies");
        }
    }
}

APIProject-MovieAPI/Views/Movie/AddFavorite.cshtml
@{
    ViewData["Title"] = "AddFavorite";
}

<h1>AddFavorite</h1>

@model IEnumerable<FavoriteMovies>


<table class="table-bordered">
    <tr>
        <th>Title</th>
        <th>Year</th>
        <th>Rated</th>
        <th>Runtime</th>
        <th>Director</th>
        <th>Genre</th>
    </tr>
    @foreach (var movie in Model)
    {
        <tr>
            <td>@movie.Title</td>
            <td>@movie.Year</td>
            <td>@movie.Rated</td>
            <td>@movie.Runtime</td>
            <td>@movie.Director</td>
            <td>@movie.Genre</td>
        </tr>
    }

</table>

APIProject-MovieAPI/Views/Movie/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

@model APIProject_MovieAPI.Models.Movie

<h1>Details</h1>
<table class="table-dark" style="border-spacing: 15px 2px; border-collapse: separate; border-color: white;">
    <tr>
        <th>Title</th>
        <th>Year</th>
        <th>Rated</th>
        <th>Runtime</th>
        <th>Director</th>
        <th>Genre</th>
    </tr>
    <tr>
        <td>@Model.Title</td>
        <td>@Model.Year</td>
        <td>@Model.Rated</td>
        <td>@Model.Runtime</td>
        <td>@Model.Director</td>
        <td>@Model.Genre</td>
        <td>@Html.ActionLink("Add to Favorites", "AddFavorite", "Movie", Model)</td>
    </tr>
    }
</table>

<img src="@Model.Poster" />

APIProject-MovieAPI/Views/Movie/DisplayMovie.cshtml
@{
    ViewData["Title"] = "DisplayMovie";
}

@model APIProject_MovieAPI.Models.Movie

<h1>DisplayMovie</h1>
@Model.Title
@Model.Year
@Model.Rated
@Model.Director
@Model.Genre
@Model.Actors

APIProject-MovieAPI/Views/Movie/FavoriteMovies.cshtml
@{
    ViewData["Title"] = "FavoriteMovies";
}
@model IEnumerable<APIProject_MovieAPI.Models.FavoriteMovies>

<h1>Favorite Movies</h1>

<table class="table-dark" style="border-spacing: 15px 2px; border-collapse: separate; border-color: white;">
    <tr>
        <th>Title</th>
        <th>Year</th>
        <th>Rated</th>
        <th>Runtime</th>
        <th>Director</th>
        <th>Genre</th>
    </tr>
    @{ foreach (var movie in Model)
        {
            <tr>
                <td>@movie.Title</td>
                <td>@movie.Year</td>
                <td>@movie.Rated</td>
                <td>@movie.Runtime</td>
                <td>@movie.Director</td>
                <td>@movie.Genre</td>
                <td>@Html.ActionLink("Remove From List", "DeleteFavorite", "Movie", movie)</td>
            </tr>
        }
    }
</table>

APIProject-MovieAPI/Views/Movie/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model APIProject_MovieAPI.Models.Movie
<h1>Search for a Movie!</h1>

<form action="/Movie/SearchByTitle" method="post">
    <input type="text" name="title"  placeholder="Title" />
    <input type="number" name="year"  placeholder="Year"/>
    <input type="submit" name="Submit" value="Submit" />
</form>

APIProject-MovieAPI/Views/Movie/SearchByTitle.cshtml
@{
    ViewData["Title"] = "SearchByTitle";
}

@model APIProject_MovieAPI.Models.MovieList
<h1>Search By Title</h1>
@{
    if (Model.Response == "True")
    {
        <table class="table-dark" style="border-spacing: 15px 2px; border-collapse: separate; border-color: white;">
            <tr>
                <th>Title</th>
                <th>Year</th>
                <th>Details</th>
            </tr>
            @foreach (var movie in Model.Search)
            {
                <tr>
                    <td>@movie.Title</td>
                    <td>@movie.Year</td>
                    <td>@Html.ActionLink("Details", "Details", "Movie", movie)</td>
                    <td>@Html.ActionLink("Add to Favorites", "AddFavorite", "Movie", movie)</td>
                </tr>
            }

        </table>
    }
    else
    {
        <p>No movie matches your search. @Html.ActionLink("Search Again", "Index", "Movie") </p>
    }
}